/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class Initialization {
  public static void LLVMInitializeTransformUtils(LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeTransformUtils(LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeScalarOpts(LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeScalarOpts(LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeVectorization(LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeVectorization(LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeInstCombine(LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeInstCombine(LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeIPO(LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeIPO(LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeInstrumentation(LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeInstrumentation(LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeAnalysis(LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeAnalysis(LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeIPA(LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeIPA(LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeCodeGen(LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeCodeGen(LLVMOpaquePassRegistry.getCPtr(R));
  }

  public static void LLVMInitializeTarget(LLVMOpaquePassRegistry R) {
    InitializationJNI.LLVMInitializeTarget(LLVMOpaquePassRegistry.getCPtr(R));
  }

}
