/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class LLVMOpaqueSize_t {
  private long swigCPtr;

  protected LLVMOpaqueSize_t(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected LLVMOpaqueSize_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(LLVMOpaqueSize_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

