/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public final class ltoCodegenModel {
  public final static ltoCodegenModel LTO_CODEGEN_PIC_MODEL_STATIC = new ltoCodegenModel("LTO_CODEGEN_PIC_MODEL_STATIC", ltoJNI.LTO_CODEGEN_PIC_MODEL_STATIC_get());
  public final static ltoCodegenModel LTO_CODEGEN_PIC_MODEL_DYNAMIC = new ltoCodegenModel("LTO_CODEGEN_PIC_MODEL_DYNAMIC", ltoJNI.LTO_CODEGEN_PIC_MODEL_DYNAMIC_get());
  public final static ltoCodegenModel LTO_CODEGEN_PIC_MODEL_DYNAMIC_NO_PIC = new ltoCodegenModel("LTO_CODEGEN_PIC_MODEL_DYNAMIC_NO_PIC", ltoJNI.LTO_CODEGEN_PIC_MODEL_DYNAMIC_NO_PIC_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ltoCodegenModel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ltoCodegenModel.class + " with value " + swigValue);
  }

  private ltoCodegenModel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ltoCodegenModel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ltoCodegenModel(String swigName, ltoCodegenModel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ltoCodegenModel[] swigValues = { LTO_CODEGEN_PIC_MODEL_STATIC, LTO_CODEGEN_PIC_MODEL_DYNAMIC, LTO_CODEGEN_PIC_MODEL_DYNAMIC_NO_PIC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

