/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public final class ltoDebugModel {
  public final static ltoDebugModel LTO_DEBUG_MODEL_NONE = new ltoDebugModel("LTO_DEBUG_MODEL_NONE", ltoJNI.LTO_DEBUG_MODEL_NONE_get());
  public final static ltoDebugModel LTO_DEBUG_MODEL_DWARF = new ltoDebugModel("LTO_DEBUG_MODEL_DWARF", ltoJNI.LTO_DEBUG_MODEL_DWARF_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ltoDebugModel swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ltoDebugModel.class + " with value " + swigValue);
  }

  private ltoDebugModel(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ltoDebugModel(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ltoDebugModel(String swigName, ltoDebugModel swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ltoDebugModel[] swigValues = { LTO_DEBUG_MODEL_NONE, LTO_DEBUG_MODEL_DWARF };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

