/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class Vectorize {
  public static void LLVMAddBBVectorizePass(LLVMOpaquePassManager PM) {
    VectorizeJNI.LLVMAddBBVectorizePass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddLoopVectorizePass(LLVMOpaquePassManager PM) {
    VectorizeJNI.LLVMAddLoopVectorizePass(LLVMOpaquePassManager.getCPtr(PM));
  }

}
