/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class Analysis {
  public static LLVMOpaqueStringRefArray new_StringArray(int nelements) {
    long cPtr = AnalysisJNI.new_StringArray(nelements);
    return (cPtr == 0) ? null : new LLVMOpaqueStringRefArray(cPtr, false);
  }

  public static void delete_StringArray(LLVMOpaqueStringRefArray ary) {
    AnalysisJNI.delete_StringArray(LLVMOpaqueStringRefArray.getCPtr(ary));
  }

  public static String StringArray_getitem(LLVMOpaqueStringRefArray ary, int index) {
    return AnalysisJNI.StringArray_getitem(LLVMOpaqueStringRefArray.getCPtr(ary), index);
  }

  public static void StringArray_setitem(LLVMOpaqueStringRefArray ary, int index, String value) {
    AnalysisJNI.StringArray_setitem(LLVMOpaqueStringRefArray.getCPtr(ary), index, value);
  }

  public static int LLVMVerifyModule(LLVMOpaqueModule M, LLVMVerifierFailureAction Action, LLVMOpaqueStringRefArray OutMessage) {
    return AnalysisJNI.LLVMVerifyModule(LLVMOpaqueModule.getCPtr(M), Action.swigValue(), LLVMOpaqueStringRefArray.getCPtr(OutMessage));
  }

  public static int LLVMVerifyFunction(LLVMOpaqueValue Fn, LLVMVerifierFailureAction Action) {
    return AnalysisJNI.LLVMVerifyFunction(LLVMOpaqueValue.getCPtr(Fn), Action.swigValue());
  }

  public static void LLVMViewFunctionCFG(LLVMOpaqueValue Fn) {
    AnalysisJNI.LLVMViewFunctionCFG(LLVMOpaqueValue.getCPtr(Fn));
  }

  public static void LLVMViewFunctionCFGOnly(LLVMOpaqueValue Fn) {
    AnalysisJNI.LLVMViewFunctionCFGOnly(LLVMOpaqueValue.getCPtr(Fn));
  }

}
