/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class Disassembler implements DisassemblerConstants {
  public static LLVMOpaqueStringRefArray new_StringArray(int nelements) {
    long cPtr = DisassemblerJNI.new_StringArray(nelements);
    return (cPtr == 0) ? null : new LLVMOpaqueStringRefArray(cPtr, false);
  }

  public static void delete_StringArray(LLVMOpaqueStringRefArray ary) {
    DisassemblerJNI.delete_StringArray(LLVMOpaqueStringRefArray.getCPtr(ary));
  }

  public static String StringArray_getitem(LLVMOpaqueStringRefArray ary, int index) {
    return DisassemblerJNI.StringArray_getitem(LLVMOpaqueStringRefArray.getCPtr(ary), index);
  }

  public static void StringArray_setitem(LLVMOpaqueStringRefArray ary, int index, String value) {
    DisassemblerJNI.StringArray_setitem(LLVMOpaqueStringRefArray.getCPtr(ary), index, value);
  }

  public static LLVMOpaqueVoid LLVMCreateDisasm(String TripleName, LLVMOpaqueVoid DisInfo, int TagType, LLVMOpaque_f_p_void_uint64_t_uint64_t_uint64_t_int_p_void__int GetOpInfo, LLVMOpaque_f_p_void_uint64_t_p_uint64_t_uint64_t_p_p_q_const__char__p_char SymbolLookUp) {
    long cPtr = DisassemblerJNI.LLVMCreateDisasm(TripleName, LLVMOpaqueVoid.getCPtr(DisInfo), TagType, LLVMOpaque_f_p_void_uint64_t_uint64_t_uint64_t_int_p_void__int.getCPtr(GetOpInfo), LLVMOpaque_f_p_void_uint64_t_p_uint64_t_uint64_t_p_p_q_const__char__p_char.getCPtr(SymbolLookUp));
    return (cPtr == 0) ? null : new LLVMOpaqueVoid(cPtr, false);
  }

  public static int LLVMSetDisasmOptions(LLVMOpaqueVoid DC, LLVMOpaqueUint64_t Options) {
    return DisassemblerJNI.LLVMSetDisasmOptions(LLVMOpaqueVoid.getCPtr(DC), LLVMOpaqueUint64_t.getCPtr(Options));
  }

  public static void LLVMDisasmDispose(LLVMOpaqueVoid DC) {
    DisassemblerJNI.LLVMDisasmDispose(LLVMOpaqueVoid.getCPtr(DC));
  }

  public static long LLVMDisasmInstruction(LLVMOpaqueVoid DC, LLVMOpaqueUint8_t Bytes, LLVMOpaqueUint64_t BytesSize, LLVMOpaqueUint64_t PC, String OutString, long OutStringSize) {
    return DisassemblerJNI.LLVMDisasmInstruction(LLVMOpaqueVoid.getCPtr(DC), LLVMOpaqueUint8_t.getCPtr(Bytes), LLVMOpaqueUint64_t.getCPtr(BytesSize), LLVMOpaqueUint64_t.getCPtr(PC), OutString, OutStringSize);
  }

}
