/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class IPO {
  public static void LLVMAddArgumentPromotionPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddArgumentPromotionPass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddConstantMergePass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddConstantMergePass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddDeadArgEliminationPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddDeadArgEliminationPass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddFunctionAttrsPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddFunctionAttrsPass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddFunctionInliningPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddFunctionInliningPass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddAlwaysInlinerPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddAlwaysInlinerPass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddGlobalDCEPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddGlobalDCEPass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddGlobalOptimizerPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddGlobalOptimizerPass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddIPConstantPropagationPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddIPConstantPropagationPass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddPruneEHPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddPruneEHPass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddIPSCCPPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddIPSCCPPass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddInternalizePass(LLVMOpaquePassManager arg0, long AllButMain) {
    IPOJNI.LLVMAddInternalizePass(LLVMOpaquePassManager.getCPtr(arg0), AllButMain);
  }

  public static void LLVMAddStripDeadPrototypesPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddStripDeadPrototypesPass(LLVMOpaquePassManager.getCPtr(PM));
  }

  public static void LLVMAddStripSymbolsPass(LLVMOpaquePassManager PM) {
    IPOJNI.LLVMAddStripSymbolsPass(LLVMOpaquePassManager.getCPtr(PM));
  }

}
