/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.jllvm.bindings;

public class LLVMOpaqueValue {
  private long swigCPtr;

  protected LLVMOpaqueValue(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected LLVMOpaqueValue() {
    swigCPtr = 0;
  }

  public static long getCPtr(LLVMOpaqueValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
  
  public static LLVMOpaqueValue newInstance(long cPtr) {
	  return cPtr == 0 ? null : new LLVMOpaqueValue(cPtr, true);
  }
}

